package di.uniba.map.b.adventure.type;

public enum CommandGUIType {
    SHOW_TEXT, CHANGE_BACKGROUND, PLAY_SOUND, ADD_INVENTORY, MOVE, TURN_ON, TURN_OFF, LOAD_GAME, HELP, END, INCREMENT_PB_VALUE, UNKNOWN, START_TIMER;
}
